(define (make-wrapper in out)
 (lambda (fn)
   (lambda (x)
     (out (fn (in x))))))                      
(define-inline (add1 x) (+ x 1))
(define-inline (sub1 x) (+ x (- 1)))
(define-inline (constfun x) 42)
(define-inline (double x) (+ x x))
(let ([wrapper (make-wrapper add1 sub1)])
 (let ([wrapconst (wrapper constfun)])
   (let ([wrapdub (wrapper double)])
     (let ([a (wrapdub 11)])
       (constfun 777)))))